# Generated by Django 6.0.6 on 2026-06-21 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(max_length=50, unique=True)),
                ('transfer_type', models.CharField(choices=[('TRANSFER', 'Transfer'), ('FORWARD', 'Forward'), ('RETURN', 'Return')], default='TRANSFER', max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Received'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=15)),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='registry.file')),
                ('from_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_sent', to='accounts.department')),
                ('from_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_initiated', to='accounts.employee')),
                ('to_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_received', to='accounts.department')),
                ('to_emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_assigned', to='accounts.employee')),
            ],
            options={
                'db_table': 'file_transfers',
                'ordering': ['-transferred_at'],
            },
        ),
    ]
