# Generated by Django 6.0.6 on 2026-07-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='expected_return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='hold_duration_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='filemovement',
            name='hold_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='filemovement',
            name='report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
